import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer";
import Link from "next/link";
import { classifiers, consonants } from "./roots/rootsStructure";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` min-h-screen ${inter.className}`}>
        <header className="flex flex-col items-center p-4">
          <h2>classifiers</h2>
          <ul>
            <li className="inline-block p-2">
              <Link href={"/"}>∅</Link>
            </li>
            {classifiers.map((classifier) => (
              <li key={classifier} className="inline-block p-2">
                <Link href={"/p/" + classifier}>{classifier}-</Link>
              </li>
            ))}
          </ul>
          <h2>radicals</h2>
          <ul>
            {consonants.map((consonant) => (
              <li key={consonant} className="inline-block p-2">
                <Link href={`/r/${consonant}a`}>/{consonant}a/</Link>
                <br />
                <Link href={`/r/${consonant}i`}>/{consonant}i/</Link>
                <br />
                <Link href={`/r/${consonant}u`}>/{consonant}u/</Link>
              </li>
            ))}
          </ul>
        </header>
        <main className="flex flex-col items-center p-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
